from django.urls import path
from . import views
urlpatterns = [
    path('',views.index,name='index'),
    path('staff/',views.staff,name='staff'),
    path('stafflogin/',views.stafflogin,name='stafflogin'),
    path('staffsignup/',views.staffsignup,name='staffsignup'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('addbook/',views.addbook,name='addbook'),
    path('SignupBackend/',views.SignupBackend,name='SignupBackend'),
    path('LoginBackend/',views.LoginBackend,name='LoginBackend'),
    path('AddBookSubmission/',views.AddBookSubmission,name='AddBookSubmission'),
    path('deletebook/<int:id>',views.deletebook,name='deletebook'),
    path('bookissue/',views.bookissue,name='bookissue'),
    path('returnbook/',views.returnbook,name='returnbook'),
    path('HandleLogout/',views.HandleLogout,name='HandleLogout'),
    path('issuebooksubmission/',views.issuebooksubmission,name='issuebooksubmission'),
    path('returnbooksubmission/',views.returnbooksubmission,name='returnbooksubmission'),
    path('Search1/',views.Search1,name='Search1'),
    path('Search2/',views.Search2,name='Search2'),
    path('Search3/',views.Search3,name='Search3'),
    path('Search4/',views.Search4,name='Search4'),
    path('SearchYear/',views.SearchYear,name='SearchYear'),
    path('Searchstudent/',views.Searchstudent,name='Searchstudent'),
    path('editbookdetails/<int:id>',views.editbookdetails,name='editbookdetails'),
    path('<int:id>/updatedetails/',views.updatedetails,name='updatedetails'),
    path('addstudent/',views.addstudent,name='addstudent'),
    path('addstudentsubmission/',views.addstudentsubmission,name='addstudentsubmission'),
    path('viewissuedbook/',views.viewissuedbook,name='viewissuedbook'),
    path('viewstudents/',views.viewstudents,name='viewstudents')
]
